name: Build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Build
      run: export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} && chmod +x gradlew && ./gradlew assembleRelease

    - name: Set current date as env variable
      run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - uses: r0adkll/sign-android-release@v1
      name: Sign APK
      with:
          releaseDirectory: app/build/outputs/apk/release/
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          output: app/build/outputs/apk/release/signed
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'
      env:
          BUILD_TOOLS_VERSION: "30.0.2"
    
    - name: Rename APK file
      run: ./.github/workflows/scripts/rename-updater.sh

    - name: Generate SHA256 checksums for the signed APK files
      run: ./.github/workflows/scripts/generate-SHA256sum.sh

    - uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.1.3"
          prerelase: false
          title: "1.1.3"
          files: |
            app/build/outputs/apk/release/app-release.apk
            build/updater-SHA-256.txt
